version: "3"
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
# WE DONT USE DHCP SERVER
#      - "68:68/udp"
      - "784:784/tcp"
      - "784:784/udp"
      - "853:853/tcp"
      - "853:853/udp"
      - "8081:80/tcp"
      #- "3000:3000/tcp"
      #- "8443:443/tcp"
#    network_mode: bridge
    volumes:
      - "${PWD}/work:/opt/adguardhome/work"
      - "${PWD}/conf:/opt/adguardhome/conf"
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      # DNS for LAN
      adguardnet:
        ipv4_address: 10.0.0.22
      # DNS for IoT
      macvlan20:
        ipv4_address: 10.0.2.22
networks:
  adguardnet:
    name: qnet-static-eth0
    external: true
  macvlan20:
    name: macvlan20
    external: true
